# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:JxQLYUNL5hJo7RzQnLhHuivmpsTh2fj2PjRGGviDZM9Ezy5+JHNokuaIvashlx7CK24v2sYfN2RUqb8QkI1JfWV10j0J2Ixl5JsA1xRKaTAOJgB+7vG5ia2RyAgJD3rt+icNwssrj+6XZ58mdyDLvwXtI0YZ79Wuu8QjvrOX/pRhhTz/tbous2Q4yQ+YLox1qIsVZkvKR48zXjxOJM1YjIa+II/34E7kdvwu4WXM29r3QEkvNw==,iv:ZAt0+Ri3u8eqZ5+wWeic6A+lWFZZJIm1WJ4rzqO8Xhw=,tag:Oh2GqH3jggE30TokBEEPEA==,type:str]
sops:
  age:
    - recipient: age1kl9zjanrpy8gxm6ewk0wmnshph00tg4d49kff4grac4jal7hxujsmsyu77
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb2M0SjVhM0xMU0JQSjBj
        Q2xROGFwbVZNbUZtYXh1OXF2TWJiZHdjOHdjCmhDd1IyNXY1Z2M4UDc2c1NPVHRO
        OXFFVjlEUFFuc1lDN1haek8vVlIyOUkKLS0tIDhlSWRRWHpWV0hEVFF0OFNTT2lC
        cVBxZXFIbjUvKzYwTnB1SVBiZjRxaGsKqa4+pEgII1a+/DD1wuktPY601KEKxqPQ
        ZDU3fkLSF3JgoQ2vbE4POkNnch04PnlhUzDNZX7FM0+E3KN5QGEiHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T20:40:48Z"
  mac: ENC[AES256_GCM,data:iDbF7ferrnvd3R0hAKloNCDUQ0G42FTSyOi51h3DXEC+g9e23hvbCTOU+TrKBDFSuTy7JClRw6c6cHnHeC4tMr2KrQ1KLd2kNKv3CubykT55Dhy6/jrSkHCN4Rx/j2aE53Zn0u4orhhixsf6bRXpBsRJvbT1ehlIsuVu0d4SONg=,iv:VODq4i702Zv4Jle4rUadyRJ73pwnO6dSNdZG3pTSbek=,tag:F5g452qJxJXTxtLtJLCCUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
