# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:4cPvLn2BNVgdECMQabL8HaTrqYVNm7fBU/H6aeoTDkkXH+IptuwUBA==,iv:YmwWEM54UsXIcZw5clJWPIHHTaJU+cq6bIqfCF23YRw=,tag:/EUxrcCC82yNiWJ62BxRkQ==,type:str]
sops:
  age:
    - recipient: age1kl9zjanrpy8gxm6ewk0wmnshph00tg4d49kff4grac4jal7hxujsmsyu77
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUGp3YjI4eXRlSWtJaWE4
        emFYVnZldGlNT2xUZzBqYzRLYS95enBXU0VBCkJqNnN6aldoY2JTbDI5VkFMaW9N
        VlFZNGtWTHZwOVF3TnB4ZVRUR2ViSm8KLS0tIEJOVlhtTGdWOU9iNUdwQ0pmMWNY
        ZklCWGZZVjNmaUd3S2lERGh3OUJ1TTgKdW5iGtoaxPormOnJNzOw53c7P7li8tvs
        YiGddGy0N6UDA+iVCneUcw5/NKPb1g76hw9XGjPSvUp4iU34p8MLzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T20:40:48Z"
  mac: ENC[AES256_GCM,data:8tNDm8du1XRbQ0xdXOLmYAHbpZPsNrrdDxF3UMhHtjEwFycS7T7eqj4HZMOI/erZiW2NTPADxlYTIcbiZhx94q2bWAP+sWFyggR0XAjbS0QZyxO5+9apDEIEXf4g2IcQrUc5mQ8mZG3ZhHEXWbcGIofXsLFBfkjQ/HSf5Z6O+2w=,iv:UkKXnuCvRXtcT5IrnZSdQDOPZAq3tZST5g1JJQxkZb0=,tag:ws/4I8ffHcE5mvdn3jGbBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
