# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:jpJiKGcCjtnE20Xp3Z8AMvdq/FTzFu+7PQ6k3DhAjzc=,iv:645HXsG6VFW3ckFGXI75V/e9SGQLHBaYtvHHdwMoBr0=,tag:12T9iPLCdQKTUtxTJsBlDw==,type:str]
sops:
  age:
    - recipient: age1kl9zjanrpy8gxm6ewk0wmnshph00tg4d49kff4grac4jal7hxujsmsyu77
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlU3A4Ui9ZN1gvUzNFQ3JR
        V0MwQU03QUx1Qmw4UVVSMnFRaTdZc1JHdjM4Cmlrc1NEM2V4M1Zqb2NkbjNjT0VJ
        cWF4QlNsNzM5N0IzSjBMMCswbFB5U2sKLS0tIElvaCtOZ2d3d2FSQ2txQmN4WUFu
        ZXpSY3dWU3UwZzVBc2pjQmx3Unk0VDgKd+TVATwtrCT5T3SmmdDP6CbpzaBoQh0l
        uWKmvqQBSMIOEeQL8xtATL0Cc0GqcNaif7B2/oCkJuoErW77Qdgw7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T22:28:19Z"
  mac: ENC[AES256_GCM,data:LoffubwnEx26ABNiCNk5bgbPLJj/+wv/nOusAjoqy/RjL19dFzIOd3iqYWiiGCHgHvgfJYV5IGpvlmGiSM9pgYajL/AMPEnfHmBpCOHDM2PdjahnX4IFcRKXX5LFVD+xa3fcJn3Hl1nWzft986DhQp2FFLLt4lj8xi2JaTt4qe4=,iv:9zu6XnbHxznS87XNSg5brQ28MprM2YzRVIayxRDPZKg=,tag:gHHOPVLyl8bNDG83o9nhxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
