apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:naCMeZxP114=,iv:IrGjAPYIMFF8fKim5BRLYFMjRTmfKTJbdY6ng2/fdv4=,tag:97XYB57Tl5nZSTfBb4TH0w==,type:str]
sops:
  age:
    - recipient: age1kl9zjanrpy8gxm6ewk0wmnshph00tg4d49kff4grac4jal7hxujsmsyu77
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYnFyWndmblZoc0N1UERN
        REwrOXEwd2Z3eWtYWlU1K2RBVGM1WEZMNndRClI0N2VMaXpQUFNNSW03S293UDZ6
        OUpVVjNJeTlGNFIxcHhIeWpobDVuMTQKLS0tIHgyVXVSK2FHcGoxbWdXU2FLcjZJ
        SGFTMWkzdVFKVnhReXIwc29KNVQ4MEUKbA56CBh7LVxuJF3n0upPocXMdSlUadLu
        oVTalvNuy9N8DToLORAr9exrGECNE6r02sm4Th58aWeWcuwODgBHsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T15:32:35Z"
  mac: ENC[AES256_GCM,data:mReiu4RgFPIIUq0FYJyrgJHM/gLrrmBtK5kfkQ0jmNJ/PiKMCA6/2h5W/mfhlbmIkm+TcbqpkvTW53oAqL7fAdwxj1hBIDBaxUMqjkAkHGQ9Z8hTE3lAiwdGnyRU7aprYLjJc6eAxd8chfuYz5MgwDUgPnPGTSCpGEKMSOZSZOo=,iv:ZO1EfOSSAEUBkSuGKhYgEkjvuiuyDrpy6rB+ej/dSec=,tag:9AKH2SzvEHJ+LwFNhreeSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
