apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:INW6WYGNVSo=,iv:9KP3asicdQr6TDQIBq/IDPVOEO6UbP+V2DUlPR5JTyA=,tag:1XfwssjFSdDp5bmfOvoSKw==,type:str]
sops:
  age:
    - recipient: age1kl9zjanrpy8gxm6ewk0wmnshph00tg4d49kff4grac4jal7hxujsmsyu77
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSW5Ic1NFU2wxWmZYVjNC
        ZXdyU3MxWkxUVUF2K3dLQldYejA4YUU2RzE4ClpEUW5YTWdORW04V053eXdHUGtH
        VGI5T0Q3U0FzRW5OUzh1S3dDNFlxVGMKLS0tIE1CT09CMkkyN0dxNzBScTRqOW54
        VUtqcEQyRlZwM3BnK2M4aHhqa2dUUzAK4F+QY5vSCnWg75F9ogGprvo/j3fglCAy
        ZC+uafggVQPIHPGm4IdtJWtcMKWgSsQ/ZN2F/q2Agu2gu2y4KSGo4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T22:28:19Z"
  mac: ENC[AES256_GCM,data:5fLWSFTvOCza0T/j5+wkM4shReDFvwO5Qi6BWzWJjwMAO8ipK0K7nyjEMmfrysOrn8Mnn/H/PxdCXxvNLgPm/JEflQmN1hC5k41hZSBQMdMPzvcQyotIau9rsTkGbUDHAuFlyOAy/okYsxJ+Cw2Roz4nt6f/9vCG6XvWJltuyCs=,iv:SWN0Oq0HPvfk2G1H2t5w1U2wIUnl7tkUay7ZVGl4TGk=,tag:BDP7Bo9WJaPL1BxOPwgJcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
