apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:a/sf+7wJUjza7XjRMer1tg==,iv:fAksszJ/oNKFNgOSU3Hc7ZpH+TUPMpJ4QK9FfkkxX/8=,tag:4dn3c1iqG5Pdt4+XUATPpQ==,type:str]
sops:
  age:
    - recipient: age1kl9zjanrpy8gxm6ewk0wmnshph00tg4d49kff4grac4jal7hxujsmsyu77
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbzE5aGNxTnVLRUdEVUdX
        L2tXaXREL1lXc1JoQVRnYjIvTWRLcnp2Y0FrClh5aTlGd3lCd2NRZFlsWXJaa2g5
        RTFzOGxEOVd3TktJMXliaTUyb2FJZzgKLS0tIFZWQ25WSkpzbHQ4YUo1K1NyK1Qw
        NDZGSzQxQkJTRWZ2cGErZjhJdWp5d2cKQT9GntZXfDisRIiYLERUgqClfGMt/8ug
        PBrlr2BKNbCg8vTFDqu2xlASHIrzSRgrITP//7jmtGRRikyCFrODYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T20:40:47Z"
  mac: ENC[AES256_GCM,data:llm6VqPxy4jW8sjsD/dfhtumx5HY71ZNmABOED2d0gJrgQMNMskiZf1kczqhthY6m3uSsqXNsW8t2g4eHftAcB03aw9IAMzN1G6g9aTZY3Dsm/f4MmhY2X80zEnRIBOVC61myAYHlZQYzoseue13J/fE+unQl0siVmxEaKxR5ZA=,iv:YTEfSd+lhhKgSak+k3obIXRYVpRtJEVDUfDfiZ18LU0=,tag:kStwCMC1NtioX0HgBWzxhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
